/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.unimontes.hm01.view;


public class TelaPrincipal extends javax.swing.JFrame {
    int xMouse, yMouse;
    TelaCadastrarCliente telaCadastrarCliente = new TelaCadastrarCliente();
    TelaCadastrarFuncionario telaCadastrarFuncionario = new TelaCadastrarFuncionario();
    TelaCadastrarServico telaCadastrarServico = new TelaCadastrarServico();
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCentral = new javax.swing.JPanel();
        jPanel_Horarios4 = new javax.swing.JPanel();
        jPainel_Registros2 = new javax.swing.JScrollPane();
        jTable_Agenda2 = new javax.swing.JTable();
        jMenuFuncionalidades = new javax.swing.JMenuBar();
        jMenu_Ferramentas = new javax.swing.JMenu();
        jMenu_Cliente = new javax.swing.JMenu();
        jMenuItem_CadastrarCliente = new javax.swing.JMenuItem();
        jMenu_Funcionario = new javax.swing.JMenu();
        jMenuItem_CadastrarFuncionario = new javax.swing.JMenuItem();
        jMenu_Servico = new javax.swing.JMenu();
        jMenuItem_CadastrarServico = new javax.swing.JMenuItem();
        jMenu_Agendamento = new javax.swing.JMenu();
        jMenuItem_RealizarAgendamento = new javax.swing.JMenuItem();
        jMenu_Sobre = new javax.swing.JMenu();
        btSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HM01 - not null");
        setIconImages(null);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(880, 500));
        setMinimumSize(new java.awt.Dimension(880, 500));
        setName("TelaPrincipal"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(880, 500));
        setResizable(false);

        jPanelCentral.setBackground(new java.awt.Color(178, 153, 115));
        jPanelCentral.setPreferredSize(new java.awt.Dimension(880, 500));

        jPanel_Horarios4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agenda", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jTable_Agenda2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jPainel_Registros2.setViewportView(jTable_Agenda2);

        javax.swing.GroupLayout jPanel_Horarios4Layout = new javax.swing.GroupLayout(jPanel_Horarios4);
        jPanel_Horarios4.setLayout(jPanel_Horarios4Layout);
        jPanel_Horarios4Layout.setHorizontalGroup(
            jPanel_Horarios4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Horarios4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPainel_Registros2, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_Horarios4Layout.setVerticalGroup(
            jPanel_Horarios4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Horarios4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPainel_Registros2, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelCentralLayout = new javax.swing.GroupLayout(jPanelCentral);
        jPanelCentral.setLayout(jPanelCentralLayout);
        jPanelCentralLayout.setHorizontalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCentralLayout.createSequentialGroup()
                .addContainerGap(623, Short.MAX_VALUE)
                .addComponent(jPanel_Horarios4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanelCentralLayout.setVerticalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentralLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel_Horarios4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jMenuFuncionalidades.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jMenuFuncionalidadesMouseDragged(evt);
            }
        });
        jMenuFuncionalidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuFuncionalidadesMousePressed(evt);
            }
        });

        jMenu_Ferramentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens.icons/cliente_icon.png"))); // NOI18N
        jMenu_Ferramentas.setText("Ferramentas");
        jMenu_Ferramentas.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N

        jMenu_Cliente.setText("Cliente");

        jMenuItem_CadastrarCliente.setText("Cadastrar Cliente");
        jMenuItem_CadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CadastrarClienteActionPerformed(evt);
            }
        });
        jMenu_Cliente.add(jMenuItem_CadastrarCliente);

        jMenu_Ferramentas.add(jMenu_Cliente);

        jMenu_Funcionario.setText("Funcionário");

        jMenuItem_CadastrarFuncionario.setText("Cadastrar Funcionário");
        jMenuItem_CadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CadastrarFuncionarioActionPerformed(evt);
            }
        });
        jMenu_Funcionario.add(jMenuItem_CadastrarFuncionario);

        jMenu_Ferramentas.add(jMenu_Funcionario);

        jMenu_Servico.setText("Serviço");

        jMenuItem_CadastrarServico.setText("Cadastrar Serviço");
        jMenuItem_CadastrarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CadastrarServicoActionPerformed(evt);
            }
        });
        jMenu_Servico.add(jMenuItem_CadastrarServico);

        jMenu_Ferramentas.add(jMenu_Servico);

        jMenu_Agendamento.setText("Agendamento");

        jMenuItem_RealizarAgendamento.setText("Realizar Agendamento");
        jMenu_Agendamento.add(jMenuItem_RealizarAgendamento);

        jMenu_Ferramentas.add(jMenu_Agendamento);

        jMenuFuncionalidades.add(jMenu_Ferramentas);

        jMenu_Sobre.setText("Sobre");
        jMenu_Sobre.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jMenuFuncionalidades.add(jMenu_Sobre);

        btSair.setText("Sair");
        btSair.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        btSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btSairMousePressed(evt);
            }
        });
        jMenuFuncionalidades.add(btSair);

        setJMenuBar(jMenuFuncionalidades);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_CadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CadastrarClienteActionPerformed
        // TODO add your handling code here:
        telaCadastrarCliente.setVisible(true);
    }//GEN-LAST:event_jMenuItem_CadastrarClienteActionPerformed

    private void jMenuItem_CadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CadastrarFuncionarioActionPerformed
        // TODO add your handling code here:
        telaCadastrarFuncionario.setVisible(true);
    }//GEN-LAST:event_jMenuItem_CadastrarFuncionarioActionPerformed

    private void jMenuItem_CadastrarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CadastrarServicoActionPerformed
        // TODO add your handling code here:
        telaCadastrarServico.setVisible(true);
    }//GEN-LAST:event_jMenuItem_CadastrarServicoActionPerformed

    private void btSairMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSairMousePressed
        System.exit(1);
    }//GEN-LAST:event_btSairMousePressed

    private void jMenuFuncionalidadesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuFuncionalidadesMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jMenuFuncionalidadesMousePressed

    private void jMenuFuncionalidadesMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuFuncionalidadesMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jMenuFuncionalidadesMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btSair;
    private javax.swing.JMenuBar jMenuFuncionalidades;
    private javax.swing.JMenuItem jMenuItem_CadastrarCliente;
    private javax.swing.JMenuItem jMenuItem_CadastrarFuncionario;
    private javax.swing.JMenuItem jMenuItem_CadastrarServico;
    private javax.swing.JMenuItem jMenuItem_RealizarAgendamento;
    private javax.swing.JMenu jMenu_Agendamento;
    private javax.swing.JMenu jMenu_Cliente;
    private javax.swing.JMenu jMenu_Ferramentas;
    private javax.swing.JMenu jMenu_Funcionario;
    private javax.swing.JMenu jMenu_Servico;
    private javax.swing.JMenu jMenu_Sobre;
    private javax.swing.JScrollPane jPainel_Registros2;
    private javax.swing.JPanel jPanelCentral;
    private javax.swing.JPanel jPanel_Horarios4;
    private javax.swing.JTable jTable_Agenda2;
    // End of variables declaration//GEN-END:variables
}
